### ISSUE TITLE
执行碰到SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by Schyliang** [NXY666/JsjiamiV6-Decryptor#45]
### 操作系统

Linux

### 问题详情

系统：Ubuntu 20.04 LTS
nodejs version 16.16.0
nodejs Decryptor.js 
/Documents/JsjiamiV6-Decryptor/Decryptor.js:1571
						if (splitStatementsRes[index + 1]?.[0] === '{') {
						                                  ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by NXY666** [comment]
我用wsl的nodejs 16.16.0运行没有问题呀，这是什么奇怪的报错...

**Comment by Schyliang** [comment]
真的奇怪，用vscode执行就没问题，用终端直接运行有这个问题。。。。

**Comment by NXY666** [comment]
我就是直接用终端运行的，也没有报错，他说的是代码语法错误，感觉是那个“?.”报的错，但nodejs16绝对已经支持这个特性了啊...

**Comment by Schyliang** [comment]
会不会是我命令有问题啊，观察发现vscode是 node Decryptor.js,我输入的命令是nodejs Decryptor.js，在终端测试发现用nodejs会报错。

**Comment by NXY666** [comment]
你用node -v看一下版本号？然后用npm run decrypt试试。

**Comment by Schyliang** [comment]
node -v  结果v16.16.0
npm run decrypt 可以成功解密

**Comment by NXY666** [comment]
有没有可能是你装了两个版本的nodejs...?

**Comment by Schyliang** [comment]
nodejs -v 结果v10.19.0
看来是我自己的环境问题

小白感谢大佬帮忙排查问题

**Comment by NXY666** [comment]
😂
